package security

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
)

const rsaKeyBits = 2048

// KeyPair wraps an RSA private key together with a stable key id (kid)
// derived from its public key, used both to sign JWTs and to publish the
// JWKS document.
type KeyPair struct {
	Private *rsa.PrivateKey
	KID     string
}

// LoadOrGenerate loads an RSA private key from <dir>/private.pem, or
// generates a new 2048-bit keypair and persists it (mode 0600) if the file
// does not exist yet.
func LoadOrGenerate(dir string) (*KeyPair, error) {
	path := filepath.Join(dir, "private.pem")

	if data, err := os.ReadFile(path); err == nil {
		key, err := parsePrivateKeyPEM(data)
		if err != nil {
			return nil, fmt.Errorf("parse existing private key %s: %w", path, err)
		}
		return &KeyPair{Private: key, KID: computeKID(&key.PublicKey)}, nil
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("read private key %s: %w", path, err)
	}

	key, err := rsa.GenerateKey(rand.Reader, rsaKeyBits)
	if err != nil {
		return nil, fmt.Errorf("generate rsa key: %w", err)
	}

	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("create keys dir %s: %w", dir, err)
	}

	pemBytes := pem.EncodeToMemory(&pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: x509.MarshalPKCS1PrivateKey(key),
	})

	if err := os.WriteFile(path, pemBytes, 0o600); err != nil {
		return nil, fmt.Errorf("persist private key %s: %w", path, err)
	}

	return &KeyPair{Private: key, KID: computeKID(&key.PublicKey)}, nil
}

func parsePrivateKeyPEM(data []byte) (*rsa.PrivateKey, error) {
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found")
	}
	if key, err := x509.ParsePKCS1PrivateKey(block.Bytes); err == nil {
		return key, nil
	}
	// Fall back to PKCS8 in case the file was generated by another tool.
	keyAny, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("unsupported private key encoding: %w", err)
	}
	rsaKey, ok := keyAny.(*rsa.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("private key is not RSA")
	}
	return rsaKey, nil
}

// computeKID derives a stable, short key id from the public key modulus and
// exponent so that it never changes across restarts for the same key, and
// changes deterministically if the key material changes.
func computeKID(pub *rsa.PublicKey) string {
	der, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		// Extremely unlikely for a valid RSA public key; fall back to a
		// hash of the modulus bytes directly.
		der = pub.N.Bytes()
	}
	sum := sha256.Sum256(der)
	return base64.RawURLEncoding.EncodeToString(sum[:])[:16]
}

// JWK is a single JSON Web Key entry (RSA public key, signature use).
type JWK struct {
	Kty string `json:"kty"`
	Use string `json:"use"`
	Alg string `json:"alg"`
	Kid string `json:"kid"`
	N   string `json:"n"`
	E   string `json:"e"`
}

// JWKS is a JSON Web Key Set document.
type JWKS struct {
	Keys []JWK `json:"keys"`
}

// JWKS builds the JWK Set document for this keypair's public key.
func (kp *KeyPair) JWKS() JWKS {
	pub := kp.Private.PublicKey
	nBytes := pub.N.Bytes()
	eBytes := bigEndianBytes(pub.E)

	return JWKS{Keys: []JWK{{
		Kty: "RSA",
		Use: "sig",
		Alg: "RS256",
		Kid: kp.KID,
		N:   base64.RawURLEncoding.EncodeToString(nBytes),
		E:   base64.RawURLEncoding.EncodeToString(eBytes),
	}}}
}

func bigEndianBytes(e int) []byte {
	if e == 0 {
		return []byte{0}
	}
	var b []byte
	for e > 0 {
		b = append([]byte{byte(e & 0xff)}, b...)
		e >>= 8
	}
	return b
}
